const mongoose = require("mongoose");

const popularNewCarAdSchema = new mongoose.Schema({
  make: { type: String },
  model: { type: String },
  mileage: { min: { type: Number }, max: { type: Number } },
  assembly: { type: String },
  bodyType: { type: String },
  engineCapacity: { min: { type: Number }, max: { type: Number } },
  price: { min: { type: Number }, max: { type: Number } },
  fuelType: { type: String },
  transmission: { type: String },
  image: { type: String },
  horsePower: { min: { type: Number }, max: { type: Number } },
  torque: { min: { type: Number }, max: { type: Number } },
  weight: { type: Number },
  groundClearence: { type: Number },
  dimensions: {
    length: { type: Number },
    width: { type: Number },
    height: { type: Number },
  },
  tyreSize: { type: Number },
  seatingCapacity: { type: Number },
  fuelTank: { type: Number },
  topSpeed: { min: { type: Number }, max: { type: Number } },
  bootSpace: { type: Number },
  variants: [
    {
      make: { type: String },
      model: { type: String },
      mileage: { min: { type: Number }, max: { type: Number } },
      price: { type: Number },
      fuelType: { type: String },
      transmission: { type: String },
      engineCapacity: { type: Number },
      image: { type: String },
      length: { type: Number },
      width: { type: Number },
      height: { type: Number },
      bootSpace: { type: Number },
      numberOfDoors: { type: Number },
      weight: { type: Number },
      wheelBase: { type: Number },
      groundClearence: { type: Number },
      seatingCapacity: { type: Number },
      turboCharger: { type: String },
      engineType: { type: String },
      horsePower: { type: Number },
      horsePowerRpm: { type: Number },
      valvesPerCylinder: { type: Number },
      fuelSystem: { type: String },
      valveMechanism: { type: String },
      compressionRatio: { type: String },
      maxSpeed: { type: Number },
      torque: { type: Number },
      torqueRpm: { type: Number },
      cylinderConfiguration: { type: String },
      driveTrain: { type: String },
      numberOfCylinders: { type: Number },
      displacement: { type: Number },
      transmissionType: { type: String },
      gearBox: { type: Number },
      steeringType: { type: String },
      minimumTurningRadius: { type: Number },
      powerAssisted: { type: String },
      frontSuspension: { type: String },
      rearSuspension: { type: String },
      frontBrakes: { type: String },
      rearBrakes: { type: String },
      wheelType: { type: String },
      wheelSize: { type: Number },
      tyreSize: { type: String }, // Changed from String to Number
      spareTyre: { type: String },
      spareTyreSize: { type: Number },
      fuelTankCapacity: { type: Number },
      cityMileage: { type: Number },
      highwayMileage: { type: Number },
      numberOfAirbags: { type: Number },
      numberOfSeatbelts: { type: Number },
      speedSensingAutoDoorLock: { type: String },
      antiTheftAlarmSystem: { type: String },
      driverSeatBeltWarning: { type: String },
      downHillAssistControl: { type: String },
      passengerSeatBeltWarning: { type: String },
      hillStartAssistControl: { type: String },
      immobilizer: { type: String },
      tractionControl: { type: String },
      doorOpeningWarning: { type: String },
      vehicleStabilityControl: { type: String },
      childLock: { type: String },
      rearFogLamp: { type: String },
      isofixChildSeatAnchors: { type: String },
      autonomousEmergencyBraking: { type: String },
      highMountStopLamp: { type: String },
      blindspotDetection: { type: String },
      antilockBrakingSystem: { type: String },
      laneDepartureWarningSystem: { type: String },
      electronicBrakeforceDistribution: { type: String },
      laneKeepAssistSystem: { type: String },
      brakeAssist: { type: String },
      airConditioner: { type: String },
      rainSensingWipers: { type: String },
      climateControl: { type: String },
      headsUpDisplay: { type: String },
      airPurifier: { type: String },
      cruiseControl: { type: String },
      rearAcVents: { type: String },
      drivingModes: { type: String },
      thirdRowAcVents: { type: String },
      paddleShifter: { type: String },
      heater: { type: String },
      keyType: { type: String },
      heatedSeats: { type: String },
      keylessEntry: { type: String },
      defogger: { type: String },
      pushStart: { type: String },
      coolBox: { type: String },
      remoteEngineStart: { type: String },
      navigation: { type: String },
      centralLocking: { type: String },
      optionalNavigation: { type: String },
      powerDoorLocks: { type: String },
      frontCamera: { type: String },
      rearCamera: { type: String },
      powerSteering: { type: String },
      powerWindows: { type: String },
      threeSixtyCamera: { type: String },
      powerMirrors: { type: String },
      frontParkingSensors: { type: String },
      autoRetractableSideMirrors: { type: String },
      rearParkingSensors: { type: String },
      powerBoot: { type: String },
      autodimmingRearViewMirror: { type: String },
      cupHolders: { type: String },
      rearCentralControl: { type: String },
      armRest: { type: String },
      rearFoldingSeat: { type: String },
      handbrake: { type: String },
      rearHeadrest: { type: String },
      autoBrakeHold: { type: String },
      rearWiper: { type: String },
      autoParkingSystem: { type: String },
      seatMaterialType: { type: String },
      interiorLighting: { type: String },
      driverSeatElectricAdjustment: { type: String },
      gloveBoxLamp: { type: String },
      driverSeatLumbarSupport: { type: String },
      cargoLight: { type: String },
      driverSeatMemoryFunction: { type: String },
      frontPowerOutlet: { type: String },
      passengerSeatElectricAdjustment: { type: String },
      rearPowerOutlet: { type: String },
      steeringAdjustment: { type: String },
      tyrePressureMonitoringSystem: { type: String },
      steeringSwitches: { type: String },
      wirelessCharger: { type: String },
      headlightOnReminder: { type: String },
      bossSeatSwitch: { type: String },
      automaticHeadLamps: { type: String },
      cdPlayer: { type: String },
      dvdPlayer: { type: String },
      numberOfSpeakers: { type: Number },
      usbAndAuxillaryCable: { type: String },
      frontSpeakers: { type: String },
      bluetoothConnectivity: { type: String },
      rearSpeakers: { type: String },
      displaySize: { type: String }, // Changed from having a string description included
      rearSeatEntertainment: { type: String },
      voiceControl: { type: String },
      androidAuto: { type: String },
      appleCarPlay: { type: String },
      alloyWheels: { type: String },
      adjustableHeadlights: { type: String },
      coloredOutsideDoorHandles: { type: String },
      rearSpoiler: { type: String },
      sideMirrorsWithIndicators: { type: String },
      sunRoof: { type: String },
      moonRoof: { type: String },
      fogLights: { type: String },
      drls: { type: String },
      roofRails: { type: String },
      sideSteps: { type: String },
      dualExhaust: { type: String },
      tachometer: { type: String },
      multiInfo: { type: String },
      informationCluster: { type: String },
    },
  ],
});

module.exports = mongoose.model("popularNewCarAd", popularNewCarAdSchema);
